# disabled_rules: # rule identifiers to exclude from running
  # - identifier_name
opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo #
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return #
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs #
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - protocol_property_accessors_order
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

included: # paths to include during linting. `--path` is ignored if present.
  - Shared
  - iOS
  - macOS
  - Tests iOS
  - Tests macOS
# excluded: # paths to ignore during linting. Takes precedence over `included`.
  # - Carthage
  # - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

type_body_length:
  - 300 # warning
  - 500 # error

function_body_length:
  warning: 40 # default
  error: 100 # default

# or they can set both explicitly
file_length:
  warning: 500
  error: 800

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
   - 3
   - 4

line_length:
  warning: 120 # default
  error: 200 # default
  ignores_comments: true

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 45
    error: 50
  excluded: iPhone # excluded via string
reporter: "xcode"

indentation: 2

deployment_target:
  iOS_deployment_target: 14.0
  macOS_deployment_target: 11.0
  watchOS_deployment_target: 7.0

enum_case_associated_values_count:
  warning: 3
  error: 4